### ISSUE TITLE
Translation is not applied in simple TS

### ISSUE THREAD

**Issue by lroellin** [ttag-org/ttag#167]
We are using ttag in normal JSX and it works perfectly.

However, we're also loading some data from TS files and ttag does not work properly there.

Working example:

```jsx
// Taste.tsx
<h2 className="title center-text">{t`Taste`}</h2>
```

Non-working example:
```jsx
// (same file)
const getTastes = () => {
    return tastes.map((taste, index) => {
      return (
        <li className="tastes" key={index}>
          <Circle size="2em" color={taste.color} />
          <p className="option">{taste.name}</p>
        </li>
      );
    });
  };

<ul>{getTastes()}</ul>

// (Taste.ts)

export const TASTE = new Map<string, ITaste>([
  ['FLORAL', { name: t`Floral`, color: '#F3B8B7' }],
```

'Floral' is still showing up as the given text.

Some things seem to be working:

* Floral is extracted to the .po file
* Floral is in the JSON file with the translation
* In the output, there is no trace of the `t`

**Comment by AlexMost** [comment]
Hi @lroellin! I suppose the problem here is that this code executed before ttag locale was applied:
```ts
export const TASTE = new Map<string, ITaste>([
  ['FLORAL', { name: t`Floral`, color: '#F3B8B7' }],
```
You should ensure that you call `useLocale` before any `ttag` functions are executed. You can look here for example: https://github.com/ttag-org/CRA-runtime-example/blob/master/app/src/App.js#L1

Here we are setting up the appropriate language in the first import of the app entry point:
```js
import './i18nInit'
```


Please, let me know if that works for you.

**Comment by lroellin** [comment]
Thanks, that was indeed the fix!

**Comment by AlexMost** [comment]
@lroellin glad that it worked for you! 100% agree that we should inform users about that issue. I have created a separate issue for this problem - https://github.com/ttag-org/ttag/issues/168

**Comment by thde** [comment]
Hey Alex, I'm working together with @lroellin on this. 

We're already setting the language in the `App.tsx` file and I know this works because the language is correct for every string within a component (`*.tsx`). For the `*.ts` files (as mentioned above) it only works when explicitly setting the language there aswell.

Do you have any idea why? As I understand it, it should be sufficient to configure it in the `App.tsx`. 🤔

**Comment by AlexMost** [comment]
Hey @thde! Please, can you check that `useLang` is called before `t` tag executes? The problem that we discussed above was happening because strings that are wrapped with `t` executed before `useLang` call.
Maybe you can also create some kind of the reproduce case to let me take a look closer to your issue?.

**Comment by lroellin** [comment]
Hi! We now fixed the issue by always setting the locale (we have a side-effecty import). Thanks!
